# Generated by Django 6.0.4 on 2026-05-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('residential', 'مسکونی'), ('commercial', 'تجاری'), ('interior', 'طراحی داخلی')], default='residential', max_length=20, verbose_name='دسته\u200cبندی')),
                ('image', models.URLField(blank=True, null=True, verbose_name='آدرس تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
            },
        ),
    ]
