# Generated by Django 6.0.4 on 2026-05-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان لینک')),
                ('url', models.CharField(max_length=500, verbose_name='آدرس لینک')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'لینک سریع',
                'verbose_name_plural': 'لینک\u200cهای سریع',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تلفن')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('working_days', models.CharField(blank=True, max_length=200, null=True, verbose_name='روزهای کاری')),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='ساعت کاری')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینکدین')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تلگرام')),
                ('newsletter_text', models.CharField(blank=True, max_length=300, null=True, verbose_name='متن خبرنامه')),
                ('copyright_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='متن کپی رایت')),
                ('designer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام طراح')),
                ('designer_link', models.URLField(blank=True, null=True, verbose_name='لینک طراح')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
