# Generated by Django 6.0.4 on 2026-05-06 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_quicklink_sitesetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickLink',
        ),
    ]
