# Generated by Django 6.0.4 on 2026-05-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_quicklink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن درباره ما'),
        ),
    ]
