# Generated by Django 6.0.4 on 2026-05-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sitesetting_about_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'اطلاعات تماس و فوتر', 'verbose_name_plural': 'اطلاعات تماس و فوتر'},
        ),
    ]
